name: my_test

on:
  push:
    branches: [ main  ]
  pull_request:
    branches: [ main  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install poetry
        run: pip install poetry

      - name: Make install and make lint
        run: |
          make install
          make lint

      - name: Tests
        run: pytest